; datatypes/datatype.r
[not datatype? 1]
[datatype! = type-of function!]
[datatype? function!]
[datatype? binary!]
[datatype? bitset!]
[datatype? block!]
[datatype? char!]
[datatype? closure!]  ; closure! =? function! in R2/Forward, R2 2.7.7+
[datatype? datatype!]
[datatype? date!]
[datatype? decimal!]
[datatype? email!]
[datatype? error!]
[datatype? event!]
[datatype? file!]
[datatype? function!]
[datatype? get-path!]  ; get-path! =? path! in R2/Forward, R2 2.7.7+
[datatype? get-word!]
[datatype? gob!]
[datatype? handle!]
[datatype? image!]
[datatype? integer!]
[datatype? issue!]
[datatype? library!]
[datatype? lit-path!]
[datatype? lit-word!]
[datatype? logic!]
[datatype? map!]  ; map! =? hash! in R2/Forward, R2 2.7.7+
[datatype? module!]
[datatype? money!]
[datatype? blank!]
[datatype? object!]
[datatype? pair!]
[datatype? group!]
[datatype? path!]
[datatype? percent!]
[datatype? port!]
[datatype? refinement!]
[datatype? set-path!]
[datatype? set-word!]
[datatype? string!]
[datatype? struct!]
[datatype? tag!]
[datatype? time!]
[datatype? tuple!]
[datatype? typeset!]  ; typeset! =? block! in R2/Forward, R2 2.7.7+
[datatype? url!]
[datatype? vector!]
[datatype? word!]
; alternative literal representation
[datatype? #[datatype! function!]]
