; datatypes/logic.r
[logic? true]
[logic? false]
[not logic? 1]
[logic! = type-of true]
[logic! = type-of false]
[true = #[true]]
[false = #[false]]
[on = true]
[off = false]
[yes = true]
[no = false]
[false = make logic! 0]
[true = make logic! 1]
[true = to logic! 0]
[true = to logic! 1]
[false = to logic! blank]
[true = to logic! "f"]
["true" = mold true]
["false" = mold false]
