[file author]
none "%host-memory.c"
none "%host-encap.c"
none "%host-encap.c"
none "%host-library.c"
none "%host-locale.c"
none "%host-browse.c"
none "%f-random.c"
none "%f-round.c"
none "%m-stack.c"
none "%host-browse.c"
none "%host-error.c"
none "%u-bmp.c"
none "%u-compress.c"
none "%host-gob.c"
none "%host-window.c"
none "%u-gif.c"
none "%sys-deci-funcs.h"
none "%sys-deci.h"
none "%s-cases.c"
none "%sys-int-funcs.h"
none "%u-png.c"
none "%host-config.c"
none "%host-time.c"
none "%host-thread.c"
"Carl Sassenrath" "%n-data.c"
"Carl Sassenrath" "%n-io.c"
"Carl Sassenrath" "%n-loop.c"
"Carl Sassenrath" "%n-math.c"
"Carl Sassenrath" "%n-sets.c"
"Carl Sassenrath" "%n-strings.c"
"Carl Sassenrath" "%n-system.c"
"Carl Sassenrath" "%p-clipboard.c"
"Carl Sassenrath" "%p-console.c"
"Carl Sassenrath" "%p-dir.c"
"Carl Sassenrath" "%p-dns.c"
"Carl Sassenrath" "%p-event.c"
"Carl Sassenrath" "%p-file.c"
"Carl Sassenrath" "%p-net.c"
"Carl Sassenrath" "%p-serial.c"
"Carl Sassenrath" "%p-timer.c"
"Carl Sassenrath" "%s-file.c"
"Carl Sassenrath" "%s-find.c"
"Carl Sassenrath" "%s-make.c"
"Carl Sassenrath" "%s-mold.c"
"Carl Sassenrath" "%s-ops.c"
"Carl Sassenrath" "%s-trim.c"
"Carl Sassenrath" "%s-unicode.c"
"Carl Sassenrath" "%t-bitset.c"
"Carl Sassenrath" "%t-block.c"
"Carl Sassenrath" "%t-char.c"
"Carl Sassenrath" "%t-datatype.c"
"Carl Sassenrath" "%t-date.c"
"Carl Sassenrath" "%t-decimal.c"
"Carl Sassenrath" "%t-event.c"
"Carl Sassenrath" "%t-function.c"
"Carl Sassenrath" "%t-gob.c"
"Carl Sassenrath" "%t-image.c"
"Carl Sassenrath" "%t-integer.c"
"Carl Sassenrath" "%t-logic.c"
"Carl Sassenrath" "%t-map.c"
"Carl Sassenrath" "%t-money.c"
"Carl Sassenrath" "%t-none.c"
"Carl Sassenrath" "%t-object.c"
"Carl Sassenrath" "%t-pair.c"
"Carl Sassenrath" "%t-port.c"
"Carl Sassenrath" "%t-string.c"
"Carl Sassenrath" "%t-time.c"
"Carl Sassenrath" "%t-tuple.c"
"Carl Sassenrath" "%t-typeset.c"
"Carl Sassenrath" "%t-vector.c"
"Carl Sassenrath" "%t-word.c"
"Carl Sassenrath" "%u-dialect.c"
"Carl Sassenrath" "%u-parse.c"
"Carl Sassenrath" "%sys-mem.h"
"Carl Sassenrath" "%reb-args.h"
"Carl Sassenrath" "%reb-codec.h"
"Carl Sassenrath" "%reb-config.h"
"Carl Sassenrath" "%reb-defs.h"
"Carl Sassenrath" "%reb-device.h"
"Carl Sassenrath" "%reb-event.h"
"Carl Sassenrath" "%reb-ext.h"
"Carl Sassenrath" "%reb-file.h"
"Carl Sassenrath" "%reb-filereq.h"
"Carl Sassenrath" "%reb-gob.h"
"Carl Sassenrath" "%reb-host.h"
"Carl Sassenrath" "%reb-math.h"
"Carl Sassenrath" "%reb-net.h"
"Carl Sassenrath" "%sys-core.h"
"Carl Sassenrath" "%sys-dec-to-char.h"
"Carl Sassenrath" "%sys-globals.h"
"Carl Sassenrath" "%sys-net.h"
"Carl Sassenrath" "%sys-scan.h"
"Carl Sassenrath" "%dev-dns.c"
"Carl Sassenrath" "%dev-net.c"
"Carl Sassenrath" "%dev-event.c"
"Carl Sassenrath" "%a-globals.c"
"Carl Sassenrath" "%a-lib.c"
"Carl Sassenrath" "%a-stubs.c"
"Carl Sassenrath" "%b-init.c"
"Carl Sassenrath" "%c-error.c"
"Carl Sassenrath" "%c-frame.c"
"Carl Sassenrath" "%c-port.c"
"Carl Sassenrath" "%c-task.c"
"Carl Sassenrath" "%c-word.c"
"Carl Sassenrath" "%d-crash.c"
"Carl Sassenrath" "%d-dump.c"
"Carl Sassenrath" "%d-print.c"
"Carl Sassenrath" "%f-blocks.c"
"Carl Sassenrath" "%f-enbase.c"
"Carl Sassenrath" "%f-extension.c"
"Carl Sassenrath" "%f-modify.c"
"Carl Sassenrath" "%f-series.c"
"Carl Sassenrath" "%f-stubs.c"
"Carl Sassenrath" "%l-scan.c"
"Carl Sassenrath" "%l-types.c"
"Carl Sassenrath" "%m-pools.c"
"Carl Sassenrath" "%m-series.c"
"Carl Sassenrath" "%n-control.c"
"Carl Sassenrath" "%host-args.c"
"Carl Sassenrath" "%host-device.c"
"Carl Sassenrath" "%host-ext-test.c"
"Carl Sassenrath" "%host-main.c"
"Carl Sassenrath" "%host-stdio.c"
"Carl Sassenrath" "%dev-serial.c"
"Carl Sassenrath" "%a-constants.c"
"Carl Sassenrath" "%dev-file.c"
"Carl Sassenrath" "%dev-stdio.c"
"Carl Sassenrath" "%host-readline.c"
"Carl Sassenrath" "%dev-clipboard.c"
"Carl Sassenrath" "%dev-event.c"
"Carl Sassenrath" "%dev-file.c"
"Carl Sassenrath" "%dev-stdio.c"
"Carl Sassenrath (REBOL interface sections)" "%s-crc.c"
"Carl Sassenrath, Joshua Shireman" "%dev-serial.c"
"Carl Sassenrath, Ladislav Mecir" "%f-math.c"
"Carl Sassenrath, Ladislav Mecir" "%reb-c.h"
"Carl Sassenrath, Ladislav Mecir, HostileFork" "%m-gc.c"
"Carl Sassenrath, Richard Smolak" "%host-lib.c"
"Carl Sassenrath, Richard Smolak, Shixin Zeng" "%host-process.c"
"Carl Sassenrath, Shixin Zeng" "%c-function.c"
"Ladislav Mecir" "%reb-dtoa.h"
"Ladislav Mecir for REBOL Technologies" "%f-deci.c"
"Richard Smolak" "%host-core.c"
"Shixin Zeng" "%dev-signal.c"
"Shixin Zeng" "%t-library.c"
"Shixin Zeng" "%f-int.c"
"Shixin Zeng" "%reb-struct.h"
"Shixin Zeng" "%t-strut.c"
"Shixin Zeng" "%t-routine.c"
"Shixin Zeng" "%p-signal.c"
