REBOL []

inp: %iso3166.txt
cnt: read inp
if #{EFBBBF} = to binary! copy/part cnt 3 [ ;UTF8 BOM
	cnt: skip cnt 3
]

;cnt: to string! cnt
;print ["string cnt BOM:" mold copy/part cnt 3]

lower: charset [#"a" - #"z"]
letter: charset [#"a" - #"z" #"A" - #"Z"]
header: {
	/*
	DO NOT EDIT
	Generated by rebol iso3166.r
	*/
	/*  code-2, country name
	*/
	const char* iso_3166_table[][2] = ^{
}
outp: %iso-3166.h
write outp header
emit: func [cnt] [
	;print ["writing" cnt]
	write/append outp cnt
]

binary-to-chex: func [
	bin [binary! any-string!]
	/local ret c
][
	print ["bin: " mold bin]
	ret: copy ""
	for-each c bin [
		append ret join "\x" skip to-hex to integer! to char! c 6
	]
	ret
]

capitalize: func [
	n
][
	ret: copy ""
	words: parse n ""
	for-each w words [
		case [
			w = "OF" [
				append ret "of "
			]
			w = "U.S." [
				append ret "U.S."
			]
			'else [
				append ret join uppercase first w reduce [lowercase next w " "]
			]
		]
	]

	remove back tail ret ;remove the extra space
	head ret
]

parse cnt [
	some [
		copy name to ";"
		";" copy code-2 to "^/"
		(emit rejoin [{^{"} code-2 {", "} binary-to-chex capitalize name {"^},^/}])
		"^/"
	]
]

emit "^};"
