REBOL []

inp: %ISO-639-2_utf-8.txt
cnt: read inp
if #{EFBBBF} = to binary! copy/part cnt 3 [ ;UTF8 BOM
    cnt: skip cnt 3
]

;cnt: to string! cnt
;print ["string cnt BOM:" mold copy/part cnt 3]

lower: charset [#"a" - #"z"]
letter: charset [#"a" - #"z" #"A" - #"Z"]
header: {
    /*
    DO NOT EDIT
    Generated by %iso639.r
    */
    /*  An alpha-3 (bibliographic) code, an alpha-3 (terminologic) code (when given), an alpha-2 code (when given), an English name, and a French name */
    const char* iso_639_table[][5] = ^{
}
outp: %iso-639.h
write outp header
emit: func [cnt] [
    ;print ["writing" cnt]
    write/append outp cnt
]

binary-to-chex: func [
    bin [binary! any-string!]
    /local ret c
][
    print ["bin:" mold bin]
    ret: copy ""
    for-each c bin [
        join ret ["\x" skip (to-hex to integer! to char! c) 6]
    ]
    ret
]

EOL: charset [#"^/" #"^M"]

parse cnt [
    some [
        ; 3-letter code
        ;
        copy temp to "|"
        (emit unspaced [{^{"} temp {"}])

        (emit ", ")

        ; "terminological code"
        ; https://en.wikipedia.org/wiki/ISO_639-2#B_and_T_codes
        ;
        "|" [
            copy temp 3 lower (emit unspaced [{"} temp {"}])
                |
            (emit "NULL")
        ]

        (emit ", ")

        ; 2-letter code
        ;
        "|" [
            copy temp 2 lower (emit unspaced [{"} temp {"}])
                |
            (emit "NULL")
        ]
        
        (emit ", ")

        ; Language name in English
        ;
        "|" copy temp to "|"
        (emit unspaced [{"} temp {"}])

        (emit ", ")

        ; Language name in French
        ;
        "|" copy temp to "^/"
        (emit unspaced [{"} binary-to-chex temp {"^},^/}])

        EOL
    ]
]

emit "^};"
