; functions/math/arcsine.r
[0 = arcsine 0]
[0 = arcsine/radians 0]
[30 = arcsine 0.5]
[(pi / 6) = arcsine/radians 0.5]
[45 = arcsine (square-root 2) / 2]
[(pi / 4) = arcsine/radians (square-root 2) / 2]
[60 = arcsine (square-root 3) / 2]
[(pi / 3) = arcsine/radians (square-root 3) / 2]
[90 = arcsine 1]
[(pi / 2) = arcsine/radians 1]
[-30 = arcsine -0.5]
[(pi / -6) = arcsine/radians -0.5]
[-45 = arcsine (square-root 2) / -2]
[(pi / -4) = arcsine/radians (square-root 2) / -2]
[-60 = arcsine (square-root 3) / -2]
[(pi / -3) = arcsine/radians (square-root 3) / -2]
[-90 = arcsine -1]
[(pi / -2) = arcsine/radians -1]
[(1e-12 / (arcsine 1e-12)) = (pi / 180)]
[(1e-9 / (arcsine/radians 1e-9)) = 1.0]
[error? try [arcsine 1.1]]
[error? try [arcsine -1.1]]
